### ISSUE TITLE
2 fails, no precise log

### ISSUE THREAD

**Issue by LordVladneutral** [foutrelis/pacmarge#2]
On a test run, it's all the log I could find...
It is repeatable though.

sudo pacmarge -n -s
:: Updating pacmarge backup file archive...
:: Attempting to merge changes to 3 file(s)
--- /dev/fd/63  2016-09-22 18:56:37.593210591 +0200
+++ /etc/locale.gen 2016-04-15 09:00:05.701299000 +0200
@@ -145,8 +145,8 @@
 #en_CA ISO-8859-1  
 #en_DK.UTF-8 UTF-8  
 #en_DK ISO-8859-1  
-#en_GB.UTF-8 UTF-8  
-#en_GB ISO-8859-1  
+en_GB.UTF-8 UTF-8  
+en_GB ISO-8859-1  
 #en_HK.UTF-8 UTF-8  
 #en_HK ISO-8859-1  
 #en_IE.UTF-8 UTF-8  
@@ -160,8 +160,8 @@
 #en_PH ISO-8859-1  
 #en_SG.UTF-8 UTF-8  
 #en_SG ISO-8859-1  
-#en_US.UTF-8 UTF-8  
-#en_US ISO-8859-1  
+en_US.UTF-8 UTF-8  
+en_US ISO-8859-1  
 #en_ZA.UTF-8 UTF-8  
 #en_ZA ISO-8859-1  
 #en_ZM UTF-8  
@@ -223,16 +223,16 @@
 #fil_PH UTF-8  
 #fo_FO.UTF-8 UTF-8  
 #fo_FO ISO-8859-1  
-#fr_BE.UTF-8 UTF-8  
-#fr_BE ISO-8859-1  
-#fr_BE@euro ISO-8859-15  
+fr_BE.UTF-8 UTF-8  
+fr_BE ISO-8859-1  
+fr_BE@euro ISO-8859-15  
 #fr_CA.UTF-8 UTF-8  
 #fr_CA ISO-8859-1  
 #fr_CH.UTF-8 UTF-8  
 #fr_CH ISO-8859-1  
-#fr_FR.UTF-8 UTF-8  
-#fr_FR ISO-8859-1  
-#fr_FR@euro ISO-8859-15  
+fr_FR.UTF-8 UTF-8  
+fr_FR ISO-8859-1  
+fr_FR@euro ISO-8859-15  
 #fr_LU.UTF-8 UTF-8  
 #fr_LU ISO-8859-1  
 #fr_LU@euro ISO-8859-15  
[WOULD MERGE] /etc/locale.gen
[FAILED] /etc/hp/hplip.conf
[FAILED] /etc/pacman.d/mirrorlist

**Comment by foutrelis** [comment]
I think the man page does an adequate job of explaining what the output means.

Sorry for the super delayed response.
